# Generated by Django 3.2.6 on 2022-04-21 16:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('title', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'job_types',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('title', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=100, null=True, verbose_name='Slug')),
                ('company_name', models.CharField(max_length=100, null=True, verbose_name='Company Name')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('description', models.CharField(max_length=600, null=True, verbose_name='Description')),
                ('remote', models.BooleanField(default=False, verbose_name='Remote')),
                ('url', models.URLField(verbose_name='URL')),
                ('location', models.CharField(max_length=100, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(verbose_name='Date Created')),
                ('job_types', models.ManyToManyField(related_name='job_types', to='core.JobType')),
                ('tags', models.ManyToManyField(related_name='tags', to='core.Tag')),
            ],
            options={
                'verbose_name_plural': 'jobs',
            },
        ),
    ]
