# Generated by Django 3.2.6 on 2022-04-21 17:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_types',
        ),
        migrations.RemoveField(
            model_name='job',
            name='tags',
        ),
        migrations.CreateModel(
            name='JobTypeLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job', models.ManyToManyField(related_name='type_job', to='core.Job')),
                ('job_types', models.ManyToManyField(related_name='job_types', to='core.JobType')),
            ],
            options={
                'verbose_name_plural': 'job_type_links',
            },
        ),
        migrations.CreateModel(
            name='JobTagLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job', models.ManyToManyField(related_name='tag_job', to='core.Job')),
                ('tag', models.ManyToManyField(related_name='tags', to='core.Tag')),
            ],
            options={
                'verbose_name_plural': 'job_tag_links',
            },
        ),
    ]
