# Generated by Django 3.2.6 on 2022-04-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220421_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=1000, null=True, verbose_name='Description'),
        ),
    ]
