# Generated by Django 3.2.6 on 2022-04-21 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220421_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtaglink',
            name='job',
        ),
        migrations.AddField(
            model_name='jobtaglink',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_job', to='core.job'),
        ),
        migrations.RemoveField(
            model_name='jobtaglink',
            name='tag',
        ),
        migrations.AddField(
            model_name='jobtaglink',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.tag'),
        ),
        migrations.RemoveField(
            model_name='jobtypelink',
            name='job',
        ),
        migrations.AddField(
            model_name='jobtypelink',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_job', to='core.job'),
        ),
        migrations.RemoveField(
            model_name='jobtypelink',
            name='job_types',
        ),
        migrations.AddField(
            model_name='jobtypelink',
            name='job_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_types', to='core.jobtype'),
        ),
    ]
