# Generated by Django 3.2.6 on 2022-04-21 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220421_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtaglink',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_job', to='core.job'),
        ),
        migrations.AlterField(
            model_name='jobtaglink',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='jobtypelink',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_job', to='core.job'),
        ),
        migrations.AlterField(
            model_name='jobtypelink',
            name='job_types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_types', to='core.jobtype'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Title'),
        ),
        migrations.AlterUniqueTogether(
            name='jobtaglink',
            unique_together={('job', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='jobtypelink',
            unique_together={('job', 'job_types')},
        ),
    ]
