# Generated by Django 3.2.6 on 2022-04-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220421_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=500, null=True, verbose_name='Location'),
        ),
    ]
